### ISSUE TITLE
Add checklist to contributing.md

### ISSUE THREAD

**Issue by olgabot** [YeoLab/flotilla#232]
Like this: https://khmer.readthedocs.org/en/latest/dev/coding-guidelines-and-review.html#checklist

Then, every pull request would have to satisfy the following checklist (copied from the link above):

```
- [ ] Is it mergable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage.
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
```

**Comment by olgabot** [comment]
done in https://github.com/YeoLab/flotilla/pull/233
